export const JOB_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  PARTIALLY_COMPLETED: "PARTIALLY_COMPLETED",
};

export const SEVERITY = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
};

export const JOB_TYPES = {
  VIDEO_EXTRACTION: "VIDEO_EXTRACTION",
  CSV_IMPORT: "CSV_IMPORT",
  TITLE_ENHANCEMENT: "TITLE_ENHANCEMENT",
  COMPETITOR_REFRESH: "COMPETITOR_REFRESH",
  QUALITY_VALIDATION: "QUALITY_VALIDATION",
};
